In [9]:
import numpy as np

In [3]:
#Zero() and Ones()
y=np.zeros((2,3))
print("Zeros:\n",y)
z=np.ones((3,2))
print("Ones:\n",z)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
x=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]],dtype = complex)

print(x)

[[10.+0.j 20.+0.j 30.+0.j]
 [40.+0.j 50.+0.j 60.+0.j]
 [70.+0.j 80.+0.j 90.+0.j]]


In [7]:
z=np.ones((3,3), dtype=[('m','int'),('n','float')])
print(z)

[[(1, 1.) (1, 1.) (1, 1.)]
 [(1, 1.) (1, 1.) (1, 1.)]
 [(1, 1.) (1, 1.) (1, 1.)]]


In [13]:
x=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9] ])
for i in x:
    for j in i:
        print(j,end=" ")
    print()

1 2 3 
4 5 6 
7 8 9 


In [15]:
x=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9] ])
print("Row 0 : ",x[0])
print("Row 1 : ",x[1])
print("Row 2 : ",x[2])

Row 0 :  [1 2 3]
Row 1 :  [4 5 6]
Row 2 :  [7 8 9]


In [17]:
print(x[::-1])

[[7 8 9]
 [4 5 6]
 [1 2 3]]
