In [1]:
import numpy as np
arr1 = np.array([
    [1,2,3], [4,5,6], [7,8,9] ])
print ("Original array:")
print(arr1)
result = np.transpose(arr1)
print("Transpose array:")
print(result)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose array:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
